package idb;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class principal_productos extends javax.swing.JFrame {
    DefaultTableModel model,model2;
            
    ArrayList<Producto> inventario = new ArrayList<>();
    Tienda miTienda = new Tienda("Esquina","Medellín");
    
    ArrayList<Trabajador> trabajadores = new ArrayList<>();
    Trabajador empleado1 = new Trabajador("Juan","123");
    Trabajador empleado2 = new Trabajador("Maria","456");
        
    Trabajador empl1 = new Trabajador();
    
    int idP;
    public principal_productos() {
        initComponents();
        FieldPassOculto.setVisible(true);
        FieldPassVisible.setVisible(false);
        
        // tablas
        model = new DefaultTableModel();
        model2 = new DefaultTableModel();
        model.addColumn("Item"); 
        model.addColumn("Producto"); 
        model.addColumn("Stock");
        model.addColumn("Precio");
        
        model2.addColumn("Código de Barras"); 
        model2.addColumn("Producto");
        model2.addColumn("Precio"); 
        model2.addColumn("Stock"); 
        
        this.TablaProductos.setModel(model);
        this.tablaVerStock.setModel(model2);
        
        trabajadores.add(empleado1);
        trabajadores.add(empleado2);
        
    }

    public boolean autenticar() {

        String user = TextUsuario.getText();
        char passArray[] = FieldPassOculto.getPassword();

        for (int i = 0; i < passArray.length; i++) {
            char c = passArray[i];
            if (!Character.isLetterOrDigit(c)) return false;
        }
        String pass = new String(passArray);
        
        boolean valido = false;
        for(Trabajador persona:trabajadores){
            valido = user.equals(persona.nombre) && pass.equals(persona.password);
            break;
        }
        return valido;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FrameStock = new javax.swing.JFrame();
        panelPrincipal2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaProductos = new javax.swing.JTable();
        PanelSuperior1 = new javax.swing.JPanel();
        LabelTienda2 = new javax.swing.JLabel();
        lblImagen = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtProducto = new javax.swing.JTextField();
        botonAgregarProducto = new javax.swing.JButton();
        txtStock = new javax.swing.JTextField();
        labelStock = new javax.swing.JLabel();
        botonEliminarF = new javax.swing.JButton();
        botonEliminar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuStock = new javax.swing.JMenu();
        FrameFactura = new javax.swing.JFrame();
        jLabel4 = new javax.swing.JLabel();
        PanelSuperior3 = new javax.swing.JPanel();
        LabelTienda4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtProducto1 = new javax.swing.JTextField();
        botonAgregarProducto1 = new javax.swing.JButton();
        labelPrecio = new javax.swing.JLabel();
        txtprecio = new javax.swing.JTextField();
        FrameChoice = new javax.swing.JFrame();
        panelChoice = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        botonActualizarInv = new javax.swing.JButton();
        botonFacturar = new javax.swing.JButton();
        botonVerInv = new javax.swing.JButton();
        PanelSuperior2 = new javax.swing.JPanel();
        LabelTienda1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        FrameVer = new javax.swing.JFrame();
        jPanel5 = new javax.swing.JPanel();
        PanelSuperior5 = new javax.swing.JPanel();
        LabelTienda5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        botonVerStock = new javax.swing.JButton();
        botonBuscar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        panelVerStock = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaVerStock = new javax.swing.JTable();
        jMenuBar2 = new javax.swing.JMenuBar();
        menuVer = new javax.swing.JMenu();
        PanelSuperior4 = new javax.swing.JPanel();
        LabelTienda3 = new javax.swing.JLabel();
        PanelPrincipal = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        PanelSuperior = new javax.swing.JPanel();
        LabelTienda = new javax.swing.JLabel();
        PanelLabelIn = new javax.swing.JPanel();
        LabelUsuario = new javax.swing.JLabel();
        LabelPass = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        TextUsuario = new javax.swing.JTextField();
        CheckPass = new javax.swing.JCheckBox();
        FieldPassOculto = new javax.swing.JPasswordField();
        FieldPassVisible = new javax.swing.JTextField();
        BotonIngresar = new javax.swing.JButton();

        FrameStock.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        FrameStock.setTitle("Actualizar Stock");

        panelPrincipal2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Item", "Nombre", "Stock", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TablaProductos);

        panelPrincipal2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 390, 320));

        PanelSuperior1.setBackground(new java.awt.Color(102, 102, 255));

        LabelTienda2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LabelTienda2.setForeground(new java.awt.Color(255, 255, 255));
        LabelTienda2.setText("Tienda de la esquina");

        javax.swing.GroupLayout PanelSuperior1Layout = new javax.swing.GroupLayout(PanelSuperior1);
        PanelSuperior1.setLayout(PanelSuperior1Layout);
        PanelSuperior1Layout.setHorizontalGroup(
            PanelSuperior1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelSuperior1Layout.createSequentialGroup()
                .addContainerGap(186, Short.MAX_VALUE)
                .addComponent(LabelTienda2)
                .addGap(124, 124, 124))
        );
        PanelSuperior1Layout.setVerticalGroup(
            PanelSuperior1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSuperior1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(LabelTienda2)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        panelPrincipal2.add(PanelSuperior1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 100));

        lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ima.jpg"))); // NOI18N
        panelPrincipal2.add(lblImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, 150, 100));

        jLabel1.setText("Nombre Producto");

        txtProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProductoActionPerformed(evt);
            }
        });

        botonAgregarProducto.setText("Agregar");
        botonAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarProductoActionPerformed(evt);
            }
        });

        txtStock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtStockKeyTyped(evt);
            }
        });

        labelStock.setText("Stock");

        botonEliminarF.setText("Eliminar Fila");
        botonEliminarF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarFActionPerformed(evt);
            }
        });

        botonEliminar.setText("Eliminar Fila Anterior");
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(botonAgregarProducto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonEliminarF)
                        .addGap(29, 29, 29))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelStock)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtProducto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtStock, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(botonEliminar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelStock)
                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAgregarProducto)
                    .addComponent(botonEliminarF))
                .addGap(18, 18, 18)
                .addComponent(botonEliminar)
                .addContainerGap(141, Short.MAX_VALUE))
        );

        panelPrincipal2.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 260, 320));

        menuStock.setText("atras");
        menuStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuStockMouseClicked(evt);
            }
        });
        menuStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuStockActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuStock);

        FrameStock.setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout FrameStockLayout = new javax.swing.GroupLayout(FrameStock.getContentPane());
        FrameStock.getContentPane().setLayout(FrameStockLayout);
        FrameStockLayout.setHorizontalGroup(
            FrameStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal2, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
        );
        FrameStockLayout.setVerticalGroup(
            FrameStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        FrameFactura.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        FrameFactura.setTitle("Facturar");
        FrameFactura.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ima.jpg"))); // NOI18N
        FrameFactura.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, 150, 100));

        PanelSuperior3.setBackground(new java.awt.Color(102, 102, 255));

        LabelTienda4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LabelTienda4.setForeground(new java.awt.Color(255, 255, 255));
        LabelTienda4.setText("Tienda de la esquina");

        javax.swing.GroupLayout PanelSuperior3Layout = new javax.swing.GroupLayout(PanelSuperior3);
        PanelSuperior3.setLayout(PanelSuperior3Layout);
        PanelSuperior3Layout.setHorizontalGroup(
            PanelSuperior3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelSuperior3Layout.createSequentialGroup()
                .addContainerGap(186, Short.MAX_VALUE)
                .addComponent(LabelTienda4)
                .addGap(124, 124, 124))
        );
        PanelSuperior3Layout.setVerticalGroup(
            PanelSuperior3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSuperior3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(LabelTienda4)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        FrameFactura.getContentPane().add(PanelSuperior3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 100));

        jLabel5.setText("Nombre Producto");

        txtProducto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProducto1ActionPerformed(evt);
            }
        });

        botonAgregarProducto1.setText("Agregar");
        botonAgregarProducto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarProducto1ActionPerformed(evt);
            }
        });

        labelPrecio.setText("Precio");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(botonAgregarProducto1)
                    .addComponent(labelPrecio))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtProducto1, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addComponent(txtprecio))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProducto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPrecio)
                    .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(botonAgregarProducto1)
                .addContainerGap(179, Short.MAX_VALUE))
        );

        FrameFactura.getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 260, 320));

        FrameChoice.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        FrameChoice.setTitle("Elija una acción");

        panelChoice.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonActualizarInv.setText("Actualizar Inventario");
        botonActualizarInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarInvActionPerformed(evt);
            }
        });

        botonFacturar.setText("Facturar compra");
        botonFacturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFacturarActionPerformed(evt);
            }
        });

        botonVerInv.setText("Ver Inventario");
        botonVerInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerInvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(botonActualizarInv)
                    .addComponent(botonVerInv))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(botonFacturar)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonActualizarInv)
                    .addComponent(botonFacturar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonVerInv))
        );

        panelChoice.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 360, 70));

        PanelSuperior2.setBackground(new java.awt.Color(102, 102, 255));

        LabelTienda1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LabelTienda1.setForeground(new java.awt.Color(255, 255, 255));
        LabelTienda1.setText("Tienda de la esquina");

        javax.swing.GroupLayout PanelSuperior2Layout = new javax.swing.GroupLayout(PanelSuperior2);
        PanelSuperior2.setLayout(PanelSuperior2Layout);
        PanelSuperior2Layout.setHorizontalGroup(
            PanelSuperior2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelSuperior2Layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(LabelTienda1)
                .addGap(95, 95, 95))
        );
        PanelSuperior2Layout.setVerticalGroup(
            PanelSuperior2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSuperior2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(LabelTienda1)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        panelChoice.add(PanelSuperior2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 100));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ima.jpg"))); // NOI18N
        panelChoice.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 130, 100));

        javax.swing.GroupLayout FrameChoiceLayout = new javax.swing.GroupLayout(FrameChoice.getContentPane());
        FrameChoice.getContentPane().setLayout(FrameChoiceLayout);
        FrameChoiceLayout.setHorizontalGroup(
            FrameChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelChoice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        FrameChoiceLayout.setVerticalGroup(
            FrameChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelChoice, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
        );

        FrameVer.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelSuperior5.setBackground(new java.awt.Color(102, 102, 255));

        LabelTienda5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LabelTienda5.setForeground(new java.awt.Color(255, 255, 255));
        LabelTienda5.setText("Tienda de la esquina");

        javax.swing.GroupLayout PanelSuperior5Layout = new javax.swing.GroupLayout(PanelSuperior5);
        PanelSuperior5.setLayout(PanelSuperior5Layout);
        PanelSuperior5Layout.setHorizontalGroup(
            PanelSuperior5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelSuperior5Layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(LabelTienda5)
                .addGap(95, 95, 95))
        );
        PanelSuperior5Layout.setVerticalGroup(
            PanelSuperior5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSuperior5Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(LabelTienda5)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel5.add(PanelSuperior5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 100));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ima.jpg"))); // NOI18N
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 150, 100));

        botonVerStock.setText("Ver");
        botonVerStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerStockActionPerformed(evt);
            }
        });

        botonBuscar.setText("Buscar Producto");
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
            .addComponent(txtBuscar)
            .addComponent(botonVerStock, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonVerStock, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(txtBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 150, 130, 170));

        tablaVerStock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código de Barras", "Producto", "Precio", "Stock"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaVerStock);

        javax.swing.GroupLayout panelVerStockLayout = new javax.swing.GroupLayout(panelVerStock);
        panelVerStock.setLayout(panelVerStockLayout);
        panelVerStockLayout.setHorizontalGroup(
            panelVerStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelVerStockLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );
        panelVerStockLayout.setVerticalGroup(
            panelVerStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVerStockLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        jPanel5.add(panelVerStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 320, 200));

        menuVer.setText("atras");
        menuVer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuVerMouseClicked(evt);
            }
        });
        menuVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVerActionPerformed(evt);
            }
        });
        jMenuBar2.add(menuVer);

        FrameVer.setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout FrameVerLayout = new javax.swing.GroupLayout(FrameVer.getContentPane());
        FrameVer.getContentPane().setLayout(FrameVerLayout);
        FrameVerLayout.setHorizontalGroup(
            FrameVerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        FrameVerLayout.setVerticalGroup(
            FrameVerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameVerLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        PanelSuperior4.setBackground(new java.awt.Color(102, 102, 255));

        LabelTienda3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LabelTienda3.setForeground(new java.awt.Color(255, 255, 255));
        LabelTienda3.setText("Tienda de la esquina");

        javax.swing.GroupLayout PanelSuperior4Layout = new javax.swing.GroupLayout(PanelSuperior4);
        PanelSuperior4.setLayout(PanelSuperior4Layout);
        PanelSuperior4Layout.setHorizontalGroup(
            PanelSuperior4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelSuperior4Layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(LabelTienda3)
                .addGap(95, 95, 95))
        );
        PanelSuperior4Layout.setVerticalGroup(
            PanelSuperior4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSuperior4Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(LabelTienda3)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login Tienda");

        PanelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ima.jpg"))); // NOI18N
        PanelPrincipal.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 140, 110));

        PanelSuperior.setBackground(new java.awt.Color(102, 102, 255));

        LabelTienda.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LabelTienda.setForeground(new java.awt.Color(255, 255, 255));
        LabelTienda.setText("Tienda de la esquina");

        javax.swing.GroupLayout PanelSuperiorLayout = new javax.swing.GroupLayout(PanelSuperior);
        PanelSuperior.setLayout(PanelSuperiorLayout);
        PanelSuperiorLayout.setHorizontalGroup(
            PanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelSuperiorLayout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addComponent(LabelTienda)
                .addGap(95, 95, 95))
        );
        PanelSuperiorLayout.setVerticalGroup(
            PanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSuperiorLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(LabelTienda)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        PanelPrincipal.add(PanelSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 110));

        LabelUsuario.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LabelUsuario.setText("Usuario");

        LabelPass.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LabelPass.setText("Contraseña");

        javax.swing.GroupLayout PanelLabelInLayout = new javax.swing.GroupLayout(PanelLabelIn);
        PanelLabelIn.setLayout(PanelLabelInLayout);
        PanelLabelInLayout.setHorizontalGroup(
            PanelLabelInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLabelInLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(PanelLabelInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelUsuario, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LabelPass, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        PanelLabelInLayout.setVerticalGroup(
            PanelLabelInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLabelInLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelUsuario)
                .addGap(18, 18, 18)
                .addComponent(LabelPass)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        PanelPrincipal.add(PanelLabelIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 170, 140));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TextUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(TextUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 112, 27));

        CheckPass.setText("Mostrar contraseña");
        CheckPass.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                CheckPassStateChanged(evt);
            }
        });
        CheckPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckPassActionPerformed(evt);
            }
        });
        jPanel1.add(CheckPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        FieldPassOculto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        FieldPassOculto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldPassOcultoActionPerformed(evt);
            }
        });
        jPanel1.add(FieldPassOculto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 110, 30));

        FieldPassVisible.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(FieldPassVisible, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 110, 30));

        PanelPrincipal.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 170, 140));

        BotonIngresar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BotonIngresar.setText("Ingresar");
        BotonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonIngresarActionPerformed(evt);
            }
        });
        PanelPrincipal.add(BotonIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextUsuarioActionPerformed

    private void CheckPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckPassActionPerformed
        
        if(CheckPass.isSelected()==true){
            FieldPassOculto.setVisible(false);
            FieldPassVisible.setVisible(true);
            FieldPassVisible.setText(String.valueOf(FieldPassOculto.getPassword()));
        }else{
            FieldPassOculto.setVisible(true);
            FieldPassVisible.setVisible(false);
        }
    }//GEN-LAST:event_CheckPassActionPerformed

    private void FieldPassOcultoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldPassOcultoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldPassOcultoActionPerformed

    private void CheckPassStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_CheckPassStateChanged
    
    }//GEN-LAST:event_CheckPassStateChanged

    private void BotonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonIngresarActionPerformed
            if (autenticar()) {
                JOptionPane.showMessageDialog(this, "Bienvenido");
                FrameChoice.setVisible(true);
                FrameChoice.setBounds(10,10,530,300); 
                this.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(this, "Nombre de usuario o contraseña no valida");
            }
    }//GEN-LAST:event_BotonIngresarActionPerformed

    private void txtProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProductoActionPerformed

    private void botonAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarProductoActionPerformed
        
        idP += 1;
        String[] datos = new String[3];
        datos[0] = String.valueOf(idP);
        datos[1] = txtProducto.getText();
        datos[2] = "1000";
        datos[3] = txtStock.getText();
        
        if(!datos[2].isEmpty()){
            model.addRow(datos);
        }
        
        txtProducto.setText("");
        txtStock.setText("");
        
        if(datos[2].isEmpty()){
            JOptionPane.showMessageDialog(this, "Ingrese un valor para el stock",
                    "Error",0);

            idP -= 1;
        }

        // guardar en inventario
        Producto nuevo = new Producto(datos[1],Integer.parseInt(datos[2]),idP);
        miTienda.inventario.add(nuevo);
   
    }//GEN-LAST:event_botonAgregarProductoActionPerformed

    private void txtProducto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProducto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProducto1ActionPerformed

    private void botonAgregarProducto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarProducto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonAgregarProducto1ActionPerformed

    private void botonActualizarInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarInvActionPerformed
        model.setRowCount(0);
        FrameStock.setVisible(true);
        FrameStock.setBounds(10,10,700,500); 
        FrameChoice.setVisible(false);
    }//GEN-LAST:event_botonActualizarInvActionPerformed

    private void botonFacturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFacturarActionPerformed
        FrameFactura.setVisible(true);
        FrameFactura.setBounds(10,10,700,500); 
        FrameChoice.setVisible(false);
    }//GEN-LAST:event_botonFacturarActionPerformed

    private void botonEliminarFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarFActionPerformed
        int fila = TablaProductos.getSelectedRow();
        if(fila >=0 ){
            model.removeRow(fila);
            miTienda.inventario.remove(fila);
            int CantidadF = TablaProductos.getRowCount();
             for (int i=fila;i<CantidadF;i++){
                idP = i+1;
                model.setValueAt(String.valueOf(idP),i,0);
                
                Producto nuevo = new Producto(miTienda.inventario.get(i).nombre,
                        miTienda.inventario.get(i).stock,idP);
                
                miTienda.inventario.set(i,nuevo);
       
            }
        }else{
            JOptionPane.showMessageDialog(this, "Seleccione una fila");
        }
    }//GEN-LAST:event_botonEliminarFActionPerformed

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        int tamano = TablaProductos.getRowCount();
        model.removeRow(tamano-1);
        miTienda.inventario.remove(tamano-1);
    }//GEN-LAST:event_botonEliminarActionPerformed

    private void txtStockKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStockKeyTyped
        char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();
    }//GEN-LAST:event_txtStockKeyTyped

    private void botonVerInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerInvActionPerformed
        FrameVer.setVisible(true);
        FrameVer.setBounds(10,10,550,400); 
        FrameChoice.setVisible(false);
    }//GEN-LAST:event_botonVerInvActionPerformed

    private void menuStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuStockActionPerformed
        
    }//GEN-LAST:event_menuStockActionPerformed

    private void menuVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVerActionPerformed
        
    }//GEN-LAST:event_menuVerActionPerformed

    private void menuVerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuVerMouseClicked
        FrameChoice.setVisible(true);
        FrameChoice.setBounds(10,10,530,300); 
        FrameVer.setVisible(false);
    }//GEN-LAST:event_menuVerMouseClicked

    private void menuStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuStockMouseClicked
        FrameChoice.setVisible(true);
        FrameChoice.setBounds(10,10,530,300); 
        FrameStock.setVisible(false);
    }//GEN-LAST:event_menuStockMouseClicked

    private void botonVerStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerStockActionPerformed
       
        // para borrar al principio
        int tamano = tablaVerStock.getRowCount();
        
        for(int i=tamano-1;i>=0;i--){
            model2.removeRow(i);
        }
        
        // recorrer inventario
        for(Producto item:miTienda.inventario){
            String[] datos = new String[3];
            datos[0] = String.valueOf(item.id);
            datos[1]= item.nombre;
            datos[2]= String.valueOf(item.stock);
            model2.addRow(datos);
        }

    }//GEN-LAST:event_botonVerStockActionPerformed

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        String busqueda = txtBuscar.getText();

        // Busca únicamente comparando el nombre
        int indice = -1;
        for (int x = 0; x < miTienda.inventario.size(); x++) {
          Producto p = miTienda.inventario.get(x);
          if (p.nombre.equals(busqueda)) {
            indice = x;
            break; // Terminar ciclo si lo encuentra
          }
        }
        
        if (indice!=-1) {
            JOptionPane.showMessageDialog(this, "El producto "+ 
                    miTienda.inventario.get(indice).nombre 
                    +" esta cargado con id "
                    + String.valueOf(miTienda.inventario.get(indice).id)+
                    " y tiene un stock de "+
                    String.valueOf(miTienda.inventario.get(indice).stock),
                    "Encontrado",1);
	}else{
            JOptionPane.showMessageDialog(this, "El producto no se encontró",
                    "No encontrado",1);
	}
        
    }//GEN-LAST:event_botonBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal_productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal_productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal_productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal_productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal_productos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonIngresar;
    private javax.swing.JCheckBox CheckPass;
    private javax.swing.JPasswordField FieldPassOculto;
    private javax.swing.JTextField FieldPassVisible;
    private javax.swing.JFrame FrameChoice;
    private javax.swing.JFrame FrameFactura;
    private javax.swing.JFrame FrameStock;
    private javax.swing.JFrame FrameVer;
    private javax.swing.JLabel LabelPass;
    private javax.swing.JLabel LabelTienda;
    private javax.swing.JLabel LabelTienda1;
    private javax.swing.JLabel LabelTienda2;
    private javax.swing.JLabel LabelTienda3;
    private javax.swing.JLabel LabelTienda4;
    private javax.swing.JLabel LabelTienda5;
    private javax.swing.JLabel LabelUsuario;
    private javax.swing.JPanel PanelLabelIn;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JPanel PanelSuperior;
    private javax.swing.JPanel PanelSuperior1;
    private javax.swing.JPanel PanelSuperior2;
    private javax.swing.JPanel PanelSuperior3;
    private javax.swing.JPanel PanelSuperior4;
    private javax.swing.JPanel PanelSuperior5;
    private javax.swing.JTable TablaProductos;
    private javax.swing.JTextField TextUsuario;
    private javax.swing.JButton botonActualizarInv;
    private javax.swing.JButton botonAgregarProducto;
    private javax.swing.JButton botonAgregarProducto1;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonEliminarF;
    private javax.swing.JButton botonFacturar;
    private javax.swing.JButton botonVerInv;
    private javax.swing.JButton botonVerStock;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelPrecio;
    private javax.swing.JLabel labelStock;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JMenu menuStock;
    private javax.swing.JMenu menuVer;
    private javax.swing.JPanel panelChoice;
    private javax.swing.JPanel panelPrincipal2;
    private javax.swing.JPanel panelVerStock;
    private javax.swing.JTable tablaVerStock;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtProducto;
    private javax.swing.JTextField txtProducto1;
    private javax.swing.JTextField txtStock;
    private javax.swing.JTextField txtprecio;
    // End of variables declaration//GEN-END:variables
}
