CREATE DATABASE pruebajoins;

CREATE TABLE Personas(
	Per INT NOT NULL AUTO_INCREMENT,
    nombre VARCHAR(45),
    apellido_1 VARCHAR(45),
    apellido_2 VARCHAR(45),
    dep INT,
    PRIMARY KEY(Per)
)ENGINE=INNODB;

CREATE TABLE Departamentos(
	dep INT NOT NULL AUTO_INCREMENT,
    departamento VARCHAR(45),
    PRIMARY KEY(dep)
)ENGINE=INNODB;

-- BORRAR TABLA
DROP TABLE Personas;
DROP TABLE Departamentos;

-- INGRESAR DATOS PERSONAS
INSERT INTO Personas VALUES(1,'ANTONIO','PEREZ','GOMEZ',1);
INSERT INTO Personas VALUES(2,'ANTONIO','GARCIA','RODRIGUEZ',2);
INSERT INTO Personas VALUES(3,'PEDRO','RUIZ','GONZALEZ',2);

-- VER TABLA
SELECT * FROM personas;

-- INGRESAR DATOS DEPARTAMENTOS
INSERT INTO Departamentos VALUES(1,'ADMINISTRACION');
INSERT INTO Departamentos VALUES(2,'INFORMATICA');
INSERT INTO Departamentos VALUES(3,'COMERCIAL');

-- VER TABLA
SELECT * FROM Departamentos;