
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class principal_productos extends javax.swing.JFrame {
    DefaultTableModel model = new DefaultTableModel(); 
    int idP;
    public principal_productos() {
        initComponents();
        FieldPassOculto.setVisible(true);
        FieldPassVisible.setVisible(false);
        
        model.addColumn("ID"); 
        model.addColumn("Producto"); 
        model.addColumn("Stock"); 
        this.TablaProductos.setModel(model);
        
    }

    public boolean autenticar() {

        String user = TextUsuario.getText();
        char passArray[] = FieldPassOculto.getPassword();

        for (int i = 0; i < passArray.length; i++) {
            char c = passArray[i];
            if (!Character.isLetterOrDigit(c)) return false;
        }
        String pass = new String(passArray);

        return user.equals("Estudiante") && pass.equals("password");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FrameStock = new javax.swing.JFrame();
        panelPrincipal2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaProductos = new javax.swing.JTable();
        PanelSuperior1 = new javax.swing.JPanel();
        LabelTienda2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtProducto = new javax.swing.JTextField();
        botonAgregarProducto = new javax.swing.JButton();
        txtStock = new javax.swing.JTextField();
        labelStock = new javax.swing.JLabel();
        FrameFactura = new javax.swing.JFrame();
        jLabel4 = new javax.swing.JLabel();
        PanelSuperior3 = new javax.swing.JPanel();
        LabelTienda4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtProducto1 = new javax.swing.JTextField();
        botonAgregarProducto1 = new javax.swing.JButton();
        labelPrecio = new javax.swing.JLabel();
        txtprecio = new javax.swing.JTextField();
        PanelPrincipal = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        PanelSuperior = new javax.swing.JPanel();
        LabelTienda = new javax.swing.JLabel();
        PanelLabelIn = new javax.swing.JPanel();
        LabelUsuario = new javax.swing.JLabel();
        LabelPass = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        TextUsuario = new javax.swing.JTextField();
        CheckPass = new javax.swing.JCheckBox();
        FieldPassOculto = new javax.swing.JPasswordField();
        FieldPassVisible = new javax.swing.JTextField();
        BotonIngresar = new javax.swing.JButton();

        FrameStock.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        FrameStock.setTitle("Actualizar Stock");

        panelPrincipal2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Stock"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TablaProductos);

        panelPrincipal2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 400, 320));

        PanelSuperior1.setBackground(new java.awt.Color(102, 102, 255));

        LabelTienda2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LabelTienda2.setForeground(new java.awt.Color(255, 255, 255));
        LabelTienda2.setText("Tienda de la esquina");

        javax.swing.GroupLayout PanelSuperior1Layout = new javax.swing.GroupLayout(PanelSuperior1);
        PanelSuperior1.setLayout(PanelSuperior1Layout);
        PanelSuperior1Layout.setHorizontalGroup(
            PanelSuperior1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelSuperior1Layout.createSequentialGroup()
                .addContainerGap(186, Short.MAX_VALUE)
                .addComponent(LabelTienda2)
                .addGap(124, 124, 124))
        );
        PanelSuperior1Layout.setVerticalGroup(
            PanelSuperior1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSuperior1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(LabelTienda2)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        panelPrincipal2.add(PanelSuperior1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 100));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ima.jpg"))); // NOI18N
        panelPrincipal2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, 150, 100));

        jLabel1.setText("Nombre Producto");

        txtProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProductoActionPerformed(evt);
            }
        });

        botonAgregarProducto.setText("Agregar");
        botonAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarProductoActionPerformed(evt);
            }
        });

        labelStock.setText("Stock");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(botonAgregarProducto)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelStock)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtProducto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtStock, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelStock)
                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(botonAgregarProducto)
                .addContainerGap(182, Short.MAX_VALUE))
        );

        panelPrincipal2.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 260, 320));

        javax.swing.GroupLayout FrameStockLayout = new javax.swing.GroupLayout(FrameStock.getContentPane());
        FrameStock.getContentPane().setLayout(FrameStockLayout);
        FrameStockLayout.setHorizontalGroup(
            FrameStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal2, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
        );
        FrameStockLayout.setVerticalGroup(
            FrameStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal2, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        FrameFactura.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        FrameFactura.setTitle("Facturar");
        FrameFactura.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ima.jpg"))); // NOI18N
        FrameFactura.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, 150, 100));

        PanelSuperior3.setBackground(new java.awt.Color(102, 102, 255));

        LabelTienda4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LabelTienda4.setForeground(new java.awt.Color(255, 255, 255));
        LabelTienda4.setText("Tienda de la esquina");

        javax.swing.GroupLayout PanelSuperior3Layout = new javax.swing.GroupLayout(PanelSuperior3);
        PanelSuperior3.setLayout(PanelSuperior3Layout);
        PanelSuperior3Layout.setHorizontalGroup(
            PanelSuperior3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelSuperior3Layout.createSequentialGroup()
                .addContainerGap(186, Short.MAX_VALUE)
                .addComponent(LabelTienda4)
                .addGap(124, 124, 124))
        );
        PanelSuperior3Layout.setVerticalGroup(
            PanelSuperior3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSuperior3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(LabelTienda4)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        FrameFactura.getContentPane().add(PanelSuperior3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 100));

        jLabel5.setText("Nombre Producto");

        txtProducto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProducto1ActionPerformed(evt);
            }
        });

        botonAgregarProducto1.setText("Agregar");
        botonAgregarProducto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarProducto1ActionPerformed(evt);
            }
        });

        labelPrecio.setText("Precio");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(botonAgregarProducto1)
                    .addComponent(labelPrecio))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtProducto1, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addComponent(txtprecio))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProducto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPrecio)
                    .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(botonAgregarProducto1)
                .addContainerGap(179, Short.MAX_VALUE))
        );

        FrameFactura.getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 260, 320));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login Tienda");

        PanelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ima.jpg"))); // NOI18N
        PanelPrincipal.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 130, 110));

        PanelSuperior.setBackground(new java.awt.Color(102, 102, 255));

        LabelTienda.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LabelTienda.setForeground(new java.awt.Color(255, 255, 255));
        LabelTienda.setText("Tienda de la esquina");

        javax.swing.GroupLayout PanelSuperiorLayout = new javax.swing.GroupLayout(PanelSuperior);
        PanelSuperior.setLayout(PanelSuperiorLayout);
        PanelSuperiorLayout.setHorizontalGroup(
            PanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelSuperiorLayout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addComponent(LabelTienda)
                .addGap(95, 95, 95))
        );
        PanelSuperiorLayout.setVerticalGroup(
            PanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSuperiorLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(LabelTienda)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        PanelPrincipal.add(PanelSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 110));

        LabelUsuario.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LabelUsuario.setText("Usuario");

        LabelPass.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LabelPass.setText("Contraseña");

        javax.swing.GroupLayout PanelLabelInLayout = new javax.swing.GroupLayout(PanelLabelIn);
        PanelLabelIn.setLayout(PanelLabelInLayout);
        PanelLabelInLayout.setHorizontalGroup(
            PanelLabelInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLabelInLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelLabelInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelUsuario, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LabelPass, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        PanelLabelInLayout.setVerticalGroup(
            PanelLabelInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLabelInLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelUsuario)
                .addGap(18, 18, 18)
                .addComponent(LabelPass)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        PanelPrincipal.add(PanelLabelIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 170, 140));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TextUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(TextUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 112, 27));

        CheckPass.setText("Mostrar contraseña");
        CheckPass.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                CheckPassStateChanged(evt);
            }
        });
        CheckPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckPassActionPerformed(evt);
            }
        });
        jPanel1.add(CheckPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        FieldPassOculto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        FieldPassOculto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldPassOcultoActionPerformed(evt);
            }
        });
        jPanel1.add(FieldPassOculto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 110, 30));

        FieldPassVisible.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(FieldPassVisible, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 110, 30));

        PanelPrincipal.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 170, 140));

        BotonIngresar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BotonIngresar.setText("Ingresar");
        BotonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonIngresarActionPerformed(evt);
            }
        });
        PanelPrincipal.add(BotonIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextUsuarioActionPerformed

    private void CheckPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckPassActionPerformed
        
        if(CheckPass.isSelected()==true){
            FieldPassOculto.setVisible(false);
            FieldPassVisible.setVisible(true);
            FieldPassVisible.setText(String.valueOf(FieldPassOculto.getPassword()));
        }else{
            FieldPassOculto.setVisible(true);
            FieldPassVisible.setVisible(false);
        }
    }//GEN-LAST:event_CheckPassActionPerformed

    private void FieldPassOcultoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldPassOcultoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldPassOcultoActionPerformed

    private void CheckPassStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_CheckPassStateChanged
    
    }//GEN-LAST:event_CheckPassStateChanged

    private void BotonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonIngresarActionPerformed
            if (autenticar()) {
                JOptionPane.showMessageDialog(this, "Bienvenido");
                FrameStock.setVisible(true);
                FrameStock.setBounds(10,10,700,500); 
                this.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(this, "Nombre de usuario o contraseña no valida");
            }
    }//GEN-LAST:event_BotonIngresarActionPerformed

    private void txtProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProductoActionPerformed

    private void botonAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarProductoActionPerformed
        idP += 1;
        String[] datos = new String[3];
        datos[0] = String.valueOf(idP);
        datos[1]=txtProducto.getText();
        datos[2]=txtStock.getText();
        model.addRow(datos);
        
        txtProducto.setText("");
        txtStock.setText("");
        
    }//GEN-LAST:event_botonAgregarProductoActionPerformed

    private void txtProducto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProducto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProducto1ActionPerformed

    private void botonAgregarProducto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarProducto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonAgregarProducto1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal_productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal_productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal_productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal_productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal_productos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonIngresar;
    private javax.swing.JCheckBox CheckPass;
    private javax.swing.JPasswordField FieldPassOculto;
    private javax.swing.JTextField FieldPassVisible;
    private javax.swing.JFrame FrameFactura;
    private javax.swing.JFrame FrameStock;
    private javax.swing.JLabel LabelPass;
    private javax.swing.JLabel LabelTienda;
    private javax.swing.JLabel LabelTienda2;
    private javax.swing.JLabel LabelTienda4;
    private javax.swing.JLabel LabelUsuario;
    private javax.swing.JPanel PanelLabelIn;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JPanel PanelSuperior;
    private javax.swing.JPanel PanelSuperior1;
    private javax.swing.JPanel PanelSuperior3;
    private javax.swing.JTable TablaProductos;
    private javax.swing.JTextField TextUsuario;
    private javax.swing.JButton botonAgregarProducto;
    private javax.swing.JButton botonAgregarProducto1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelPrecio;
    private javax.swing.JLabel labelStock;
    private javax.swing.JPanel panelPrincipal2;
    private javax.swing.JTextField txtProducto;
    private javax.swing.JTextField txtProducto1;
    private javax.swing.JTextField txtStock;
    private javax.swing.JTextField txtprecio;
    // End of variables declaration//GEN-END:variables
}
